services:
  bootloader-dev:
    image: bootloader-dev
    container_name: bootloader-dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/bootloader
      - /dev:/dev # This is needed to access virtualization devices for QEMU (e.g. /dev/kvm on Linux).
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true # This is needed to access all devices in /dev.
    network_mode: "host"
